### ISSUE TITLE
Float waveform PVs are displayed to the wrong precision

### ISSUE THREAD

**Issue by rjwills28** [ornl-epics/pvws#21]
We have been testing pvws/dbwr with an EPICS waveform PV of type FLOAT, e.g.
```
record(waveform, "TEST:ARR0")
{
    field(NELM,"10")
    field(FTVL, "FLOAT")
}
```
This PV is displayed as expected in **Phoebus**, i.e.
![phoebus_float_waveform](https://github.com/ornl-epics/pvws/assets/45264327/03cba983-b461-4214-b2e6-fcc72d88bf5e)

However when the same BOB file is displayed in **dbwr**, the array values are given to a much higher precision which is misleading, i.e.
![dbwr_float_waveform](https://github.com/ornl-epics/pvws/assets/45264327/910d6d17-9ddf-4604-849b-a3c78aec6831)

I have checked the pvws response and confirmed that this misleading array is what is sent back to the client therefore I think the issue lies in pvws. Note that we do **not** see this issue when using a waveform PV of type DOUBLE. 

pvws tries to handle a FloatArray in the same way as it does for a DoubleArray however this doesn't seem to work. I think the problem is coming from the inherent way that floats are stored meaning that the value can change from the original (i.e.. the 'float precision issue'). I have found a way around this which minimizes the impact on the rest of the code. This includes converting the float to a string and then parsing as a double. 
I have forked and created a branch with this fix - please see: https://github.com/ornl-epics/pvws/compare/main...rjwills28:pvws:float_waveform_fix. I have created a new method to handle floats based on `handleDoubles`, which handles the float values differently (see line 264+265 in above branch).

**Comment by kasemir** [comment]
The example seems beyond the point. Your waveform record doesn't configure any display precision.
The widgets with default, pre -1 also don't configure anything.
So the widget may display the value any way it pleases.
Converting the float to a string and then parsing as a double seems like a hack to work around something that's undefined.


If you want to display floats with two digits, configure PREC=2 on the record. The PVWS then needs to send the number with display metadata that has precision=2, but the values are simply the "Float.toString" representation, since we do want to send the actual data, and the precision is a display hint.

Then make the widget use the precision to format the numbers.

**Comment by rjwills28** [comment]
I have configured the float record to have PREC=3, e.g.
```
record(waveform, "TEST:ARR0")
{
    field(NELM,"10")
    field(PREC, 3)
    field(FTVL, "FLOAT")
}
```
The results are similar, even if I change the `precision` in the widget from `-1` to `3` to dictate the precision. See example below:

**caput**
`caput -a TEST:ARR0 10 2.346 3.45`

**Phoebus**
![phoebus_float_waveform_prec](https://github.com/ornl-epics/pvws/assets/45264327/465fc0af-78c0-4154-a0d8-0d2a45487acc)
**DBWR**
![dbwr_float_waveform_prec](https://github.com/ornl-epics/pvws/assets/45264327/cb016adb-6258-41ba-a868-5a58b85ace21)

So is the issue actually with DBWR and that it is not yet using the precision specified in the widget (or the PREC field in the case precision is `-1`) to configure the display? I still think that the information sent from PVWS is misleading as it doesn't represent the actual data and if I were to set the precision of the widget to a higher number I would start to see those spurious numbers instead of 0s.

**Comment by kasemir** [comment]
Thanks for updating PVWS and DBWR to better handle the various array data types!

> .. precision.. to 8 .. spurious values ..  same result in Phoebus.
> .. feature of floating point numbers that cannot be represented correctly.

Exactly. Check the basics of floating point numbers, like https://en.wikipedia.org/wiki/Single-precision_floating-point_format:
"All integers with 7 or fewer decimal digits.. can be converted exactly into an IEEE 754 single-precision floating-point value."

In other words, you can at most have 7 significant digits for a float.
See this Java example that shows how trying to add two numbers gives a slightly wrong result as we exceed 7 digits overall:
```
        // There is a "float" data type, because that's what was used to store
        // floating point numbers way back, but it's not very accurate.
        float f1 = 99999.8f;
        float f2 = 99999.65f;
        // This should compute to 199999.45, but will print .44
        System.out.println(f1 + f2);
        if (f1 + f2  ==  199999.45f)
            System.out.println("What are you talking about, looks good to me?!");
        else
            System.out.println("Houston, we really do have a problem...");
```

That's why almost all floating point math is now done in `double`, with maybe two exceptions:
Some embedded system that has no floating point unit, so `float` or even a fixed-point integer is much faster,
and array transfers. For the latter, you transfer `float` arrays when they're "good enough" and of course smaller = faster. When then using that data to compute stuff, you likely do that in `double`.
